### ISSUE TITLE
the py cannot run on windows 10

### ISSUE THREAD

**Issue by yonghuming** [jbaragry/mcpi-scratch#5]
i run mcpi-scratch.py on my windows 10 computer,and got this error
if ` message = '\r\n'.join(message_parts)`
if add str to 
` message = '\r\n'.join(str(message_parts))`
i could not get it work either, i love you project and your work and want to help, i do not know how soon you could see my question
`D:\MinecraftServer>py -2 mcpi-scratch.py
INFO:__main__:Namespace(host=None)
INFO:__main__:Starting server, use <Ctrl-C> to stop
DEBUG:__main__:poll: 1
DEBUG:__main__:call mc
DEBUG:__main__:Vec3(13,4,1)
DEBUG:__main__:pollResp: 13
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 58809)
Traceback (most recent call last):
  File "C:\Python27\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python27\lib\SocketServer.py", line 655, in __init__
    self.handle()
  File "C:\Python27\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "C:\Python27\lib\BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "mcpi-scratch.py", line 296, in do_GET
    message = '\r\n'.join(message_parts)
TypeError: sequence item 1: expected string, int found
----------------------------------------
DEBUG:__main__:poll: 2
DEBUG:__main__:call mc
DEBUG:__main__:Vec3(13,4,1)
DEBUG:__main__:pollResp: 13
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 58811)
Traceback (most recent call last):
  File "C:\Python27\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python27\lib\SocketServer.py", line 655, in __init__
    self.handle()
  File "C:\Python27\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "C:\Python27\lib\BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "mcpi-scratch.py", line 296, in do_GET
    message = '\r\n'.join(message_parts)
TypeError: sequence item 1: expected string, int found
----------------------------------------
DEBUG:__main__:poll: 3
DEBUG:__main__:call mc
DEBUG:__main__:Vec3(13,4,1)
DEBUG:__main__:pollResp: 13`

**Comment by jbaragry** [comment]
Hi,
mcpi-scratch is created with python3. I haven't tested on python2.x
Is it possible for you to upgrade your version of python?
